databaseinventory/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from users import views as usr_views
from mssql import views as tsql_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    url(r'^mssql/', include('mssql.urls',namespace='mssql'), name='mssql'),
    url(r'^users/', include('users.urls',namespace='users'), name='users'),
    url(r'^logout/$', usr_views.user_logout, name = 'logout'),
]

admin.site.site_header = 'DbInventory administration'

mssql/urls.py
# from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url
from mssql import views

# TEMPLATE URLS!
app_name = 'mssql'


# https://docs.djangoproject.com/en/2.1/ref/urls/
# https://docs.djangoproject.com/en/2.1/topics/http/urls/
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), 
    # dbo.Application
    path('application/',views.ApplicationListView.as_view(),name='application'),
    path('application/<int:pk>/', views.ApplicationDetailView.as_view(),name='applicationdetail'),
    path('application/create/', views.ApplicationCreateView.as_view(), name='applicationcreate'),
    path('application/update/<int:pk>/', views.ApplicationUpdateView.as_view(), name='applicationupdate'),
    path('application/delete/<int:pk>/', views.ApplicationDeleteView .as_view(), name='applicationdelete'),
    # dbo.Server
    # path('server/',views.server,name='server'),
    path('server/',views.ServerListView.as_view(),name='server'),
    path('server/<int:pk>/', views.ServerDetailView.as_view(),name='serverdetail'),
    path('server/create/', views.ServerCreateView.as_view(), name='servercreate'),
    path('server/update/<int:pk>/', views.ServerUpdateView.as_view(), name='serverupdate'),
    path('server/delete/<int:pk>/', views.ServerDeleteView .as_view(), name='serverdelete'),
    # dbo.Instance
    path('instance/', views.InstanceListView.as_view(), name='instance'),
    path('instance/<int:pk>/', views.InstanceDetailView.as_view(),name='instancedetail'),
    path('instance/create/', views.InstanceCreateView.as_view(), name='instancecreate'),
    path('instance/update/<int:pk>/', views.InstanceUpdateView.as_view(), name='instanceupdate'),
    path('instance/delete/<int:pk>/', views.InstanceDeleteView .as_view(), name='instancedelete'),
    # dbo.Databases
    path('database/', views.DatabaseListView.as_view(), name='database'),
    path('database/<int:pk>/', views.DatabaseDetailView.as_view(),name='databasedetail'),
    path('database/create/', views.DatabaseCreateView.as_view(), name='databasecreate'),
    path('database/update/<int:pk>/', views.DatabaseUpdateView.as_view(), name='databaseupdate'),
    path('database/delete/<int:pk>/', views.DatabaseDeleteView .as_view(), name='databasedelete'),
    # dbo.Backupschedule
    path('backupschedule/',views.BackupscheduleListView.as_view(),name='backupschedule'),
    path('backupschedule/<int:pk>/', views.BackupscheduleDetailView.as_view(),name='backupscheduledetail'),
    path('backupschedule/create/', views.BackupscheduleCreateView.as_view(), name='backupschedulecreate'),
    path('backupschedule/update/<int:pk>/', views.BackupscheduleUpdateView.as_view(), name='backupscheduleupdate'),
    path('backupschedule/delete/<int:pk>/', views.BackupscheduleDeleteView .as_view(), name='backupscheduledelete'),
    # dbo.Commandqueue
    path('commandqueue/',views.CommandqueueListView.as_view(),name='commandqueue'),
    path('commandqueue/<int:pk>/', views.CommandqueueDetailView.as_view(),name='commandqueuedetail'),
    path('commandqueue/create/', views.CommandqueueCreateView.as_view(), name='commandqueuecreate'),
    path('commandqueue/update/<int:pk>/', views.CommandqueueUpdateView.as_view(), name='commandqueueupdate'),
    path('commandqueue/delete/<int:pk>/', views.CommandqueueDeleteView .as_view(), name='commandqueuedelete'),
    # dbo.Logging
    path('logging/', views.LoggingListView.as_view(), name='logging'),
    path('logging/<int:pk>/', views.LoggingDetailView.as_view(),name='loggingdetail'),
    path('logging/create/', views.LoggingCreateView.as_view(), name='loggingcreate'),
    path('logging/update/<int:pk>/', views.LoggingUpdateView.as_view(), name='loggingupdate'),
    path('logging/delete/<int:pk>/', views.LoggingDeleteView .as_view(), name='loggingdelete'),
    # dbo.Backuphistory
    path('backuphistory/', views.BackuphistoryListView.as_view(), name='backuphistory'),
    path('backuphistory/<int:pk>/', views.BackuphistoryDetailView.as_view(),name='backuphistorydetail'),
]

mssql/views.py
from django.shortcuts import render
from . import models
from django.db.models import Q
from django.db import connection
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from databaseinventory.utils import dictfetchall
from django.urls import reverse, reverse_lazy


class IndexView(TemplateView):
    template_name = 'mssql/index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['databaseinventory'] = models.databaseinventory
        context['servermaintenance'] = models.servermaintenance
        return context


def server(request):
    cursor = connection.cursor()
    try:
        cursor.execute("""
select  ServerID, ServerName, ApplicationId, 
        EnvironmentType, FQDN, IPAddress, Domain, 
        IsStandaloneServer, IsSqlClusterNode, IsAgNode, IsWSFC, 
        IsSqlCluster, IsAG, ParentServerId, OS, 
        SPVersion, IsVM, IsPhysical, Manufacturer, 
        Model, RAM, CPU, Powerplan, 
        OSArchitecture, ISDecom, DecomDate, GeneralDescription, 
        Remark1, Remark2, CollectionDate, CollectedBy, 
        UpdatedDate, UpdatedBy
from Server
""")
        # https://stackoverflow.com/a/14294314/4449743
        serverData = dictfetchall(cursor)
    # catch:
        #raise ValueError('Could not fetch data from INFORMATION_SCHEMA.COLUMNS')
    finally:
        cursor.close()

    servers = {'serverData': serverData}
    return render(request, 'mssql/server.html', context=servers)


def instance(request):
    cursor = connection.cursor()
    try:
        cursor.execute("""
SELECT	i.[InstanceID]
      ,s.ServerName
      ,i.[SqlInstance]
      ,i.[InstanceName]
      ,i.[RootDirectory]
      ,i.[Version]
      ,i.[CommonVersion]
      ,i.[Build]
      ,i.[VersionString]
      ,i.[Edition]
      ,i.[Collation]
      ,i.[ProductKey]
      ,i.[DefaultDataLocation]
      ,i.[DefaultLogLocation]
      ,i.[DefaultBackupLocation]
      ,i.[ErrorLogPath]
      ,i.[ServiceAccount]
      ,i.[Port]
      ,i.[IsStandaloneInstance]
      ,i.[IsSQLCluster]
      ,i.[IsAGListener]
      ,i.[IsAGNode]
      ,i.[AGListener]
      ,i.[HasOtherHASetup]
      ,i.[HARole]
      ,i.[HAPartner]
      ,i.[IsPowershellLinked]
      ,i.[IsDecom]
      ,i.[DecomDate]
      ,i.[CollectionDate]
      ,i.[CollectedBy]
      ,i.[UpdatedDate]
      ,i.[UpdatedBy]
      ,i.[Remark1]
      ,i.[Remark2]
FROM	Instance as i
INNER JOIN
		Server as s
	ON	s.ServerID = i.ServerID
WHERE   i.IsDecom = 0 or i.IsDecom IS NULL
        """)
        # https://stackoverflow.com/a/14294314/4449743
        instanceData = dictfetchall(cursor)
    # catch:
        #raise ValueError('Could not fetch data from INFORMATION_SCHEMA.COLUMNS')
    finally:
        cursor.close()

    instances = {'instanceData': instanceData}
    return render(request, 'mssql/instance.html', context=instances)


class ApplicationListView(ListView):
    context_object_name = 'applications'
    model = models.Application

class ApplicationDetailView(DetailView):
    context_object_name = 'application_detail'
    model = models.Application
    
    template_name = 'mssql/application_detail.html'

class ApplicationCreateView(CreateView):
    model = models.Application
    fields = ['category','businessunit','applicationname','priority','businessowner','technicalowner','secondarytechnicalowner','remark1','remark2']

class ApplicationUpdateView(UpdateView):
    model = models.Application
    fields = ['category','businessunit','applicationname','priority','businessowner','technicalowner','secondarytechnicalowner','remark1','remark2']

class ApplicationDeleteView(DeleteView):
    model = models.Application
    success_url = reverse_lazy("mssql:application")


class ServerListView(ListView):
    context_object_name = 'servers'
    model = models.Server

    def get_queryset(self):
        # https://docs.djangoproject.com/en/2.1/ref/models/querysets/#select-related
        # return models.Server.objects.select_related('applicationid').filter(Q(isdecom=0) | Q(isdecom=None))
        return models.Server.objects.prefetch_related('applicationid').filter(Q(isdecom=0) | Q(isdecom=None))

class ServerDetailView(DetailView):
    context_object_name = 'server_detail'
    model = models.Server
    
    template_name = 'mssql/server_detail.html'

class ServerCreateView(CreateView):
    model = models.Server
    fields = ['servername','applicationid','environmenttype','fqdn','ipaddress','domain','isstandaloneserver','issqlclusternode','isagnode','iswsfc','issqlcluster','isag','parentserverid','os','spversion','isvm','isphysical','manufacturer','model','ram','cpu','powerplan','osarchitecture','generaldescription','remark1','remark2']

class ServerUpdateView(UpdateView):
    model = models.Server
    fields = ['servername','applicationid','environmenttype','fqdn','ipaddress','domain','isstandaloneserver','issqlclusternode','isagnode','iswsfc','issqlcluster','isag','parentserverid','os','spversion','isvm','isphysical','manufacturer','model','ram','cpu','powerplan','osarchitecture','isdecom','decomdate','generaldescription','remark1','remark2']

class ServerDeleteView(DeleteView):
    model = models.Server
    success_url = reverse_lazy("mssql:server")


class InstanceListView(ListView):
    context_object_name = 'instances'
    model = models.Instance

    def get_queryset(self):
        return models.Instance.objects.prefetch_related('serverid','aglistener','hapartner').filter(Q(isdecom=0) | Q(isdecom=None))

class InstanceDetailView(DetailView):
    context_object_name = 'instance_detail'
    model = models.Instance
    
    template_name = 'mssql/instance_detail.html'

class InstanceCreateView(CreateView):
    model = models.Instance
    fields = ['serverid','sqlinstance','instancename','rootdirectory','version','commonversion','build','versionstring','edition','collation','productkey','defaultdatalocation','defaultloglocation','defaultbackuplocation','errorlogpath','serviceaccount','port','isstandaloneinstance','issqlcluster','isaglistener','isagnode','aglistener','hasotherhasetup','harole','hapartner','ispowershelllinked','remark1','remark2']

class InstanceUpdateView(UpdateView):
    model = models.Instance
    fields = ['serverid','sqlinstance','instancename','rootdirectory','version','commonversion','build','versionstring','edition','collation','productkey','defaultdatalocation','defaultloglocation','defaultbackuplocation','errorlogpath','serviceaccount','port','isstandaloneinstance','issqlcluster','isaglistener','isagnode','aglistener','hasotherhasetup','harole','hapartner','ispowershelllinked','isdecom','decomdate','remark1','remark2']

class InstanceDeleteView(DeleteView):
    model = models.Instance
    success_url = reverse_lazy("mssql:instance")



class DatabaseListView(ListView):
    context_object_name = 'databases'
    model = models.Database

    def get_queryset(self):
        return models.Database.objects.prefetch_related('instanceid')

class DatabaseDetailView(DetailView):
    context_object_name = 'database_detail'
    model = models.Database
    
    template_name = 'mssql/database_detail.html'

class DatabaseCreateView(CreateView):
    model = models.Database
    fields = ['instanceid','databasename','createddate','recoverymodel','currentdbsize','backuppath']

class DatabaseUpdateView(UpdateView):
    model = models.Database
    fields = ['instanceid','databasename','createddate','recoverymodel','currentdbsize','backuppath']

class DatabaseDeleteView(DeleteView):
    model = models.Database
    success_url = reverse_lazy("mssql:database")



class BackupscheduleListView(ListView):
    context_object_name = 'backupschedules'
    model = models.Backupschedule

    def get_queryset(self):
        return models.Backupschedule.objects.prefetch_related('instanceid')

class BackupscheduleDetailView(DetailView):
    context_object_name = 'backupschedule_detail'
    model = models.Backupschedule
    
    template_name = 'mssql/backupschedule_detail.html'

class BackupscheduleCreateView(CreateView):
    model = models.Backupschedule
    fields = ['instanceid','timefrom','timeto']

class BackupscheduleUpdateView(UpdateView):
    model = models.Backupschedule
    fields = ['instanceid','timefrom','timeto']

class BackupscheduleDeleteView(DeleteView):
    model = models.Backupschedule
    success_url = reverse_lazy("mssql:backupschedule")


class CommandqueueListView(ListView):
    context_object_name = 'commandqueues'
    model = models.Commandqueue

    def get_queryset(self):
        return models.Commandqueue.objects.prefetch_related('instanceid','databaseid')

class CommandqueueDetailView(DetailView):
    context_object_name = 'commandqueue_detail'
    model = models.Commandqueue
    
    template_name = 'mssql/commandqueue_detail.html'

class CommandqueueCreateView(CreateView):
    model = models.Commandqueue
    fields = ['instanceid','databaseid','command','jobid','jobtype','status','reason','priority']

class CommandqueueUpdateView(UpdateView):
    model = models.Commandqueue
    fields = ['instanceid','databaseid','command','jobid','jobtype','status','reason','priority']

class CommandqueueDeleteView(DeleteView):
    model = models.Commandqueue
    success_url = reverse_lazy("mssql:commandqueue")



class LoggingListView(ListView):
    context_object_name = 'loggings'
    model = models.Logging

class LoggingDetailView(DetailView):
    context_object_name = 'logging_detail'
    model = models.Logging
    
    template_name = 'mssql/logging_detail.html'

class LoggingCreateView(CreateView):
    model = models.Logging
    fields = ['logid','logmessage']

class LoggingUpdateView(UpdateView):
    model = models.Logging
    fields = ['logid','logmessage']

class LoggingDeleteView(DeleteView):

mssql/templates/mssql/folder/object_confirm_delete.html
{% extends "mssql/mssql_base.html" %}
{% load staticfiles %}


{% block block_navigation %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:index' %}">MSSQL</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:server' %}">Server</a></li>
      <li class="breadcrumb-item active" aria-current="page">Delete</li>
    </ol>
  </nav>
{% endblock block_navigation %}

{% block block_body %}
  <div class="container">
    <div class="card">
      <h5 class="alert alert-danger" role="alert">Confirm</h5>
      <div class="card-body">
        <div class="alert alert-warning" role="alert">
          Tip! Instead of deleting the server, you can mark it as 'decommissioned'
        </div>

        <h3 class="card-title">Proceed to Delete Server [{{server.servername}}]?</h3>
        
        <form method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-danger" value="Delete">
          <a href="{% url 'mssql:serverdetail' pk=server.pk %}" class="btn btn-info">Cancel</a>
        </form>
      
      </div>
    </div>
  </div>
{% endblock block_body %}

mssql/templates/mssql/folder/object_detail.html
{% extends "mssql/mssql_base.html" %}
{% load staticfiles %}

{% block block_navigation %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:index' %}">MSSQL</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:server' %}">Server</a></li>
      <li class="breadcrumb-item active" aria-current="page">Server Details</li>
    </ol>
  </nav>
{% endblock block_navigation %}

{% block block_body %}
  <div class="container">
    <div class="card">
      <h5 class="card-header bg-success">Welcome to Server Detail Page</h5>
      <div class="card-body">
        <h5 class="card-title text-primary">Server details:</h5>
        <p class="card-text">
          <table class="table table-bordered table-striped dbinventorytable-detail">
            <tbody>
              <tr class=""><td>ServerID</td><td>{{server_detail.serverid}}</td></tr>
              <tr class=""><td>ServerName</td><td>{{server_detail.servername}}</td></tr>
              <tr class=""><td>ApplicationId</td><td>{{server_detail.applicationid}}</td></tr>
              <tr class=""><td>EnvironmentType</td><td>{{server_detail.environmenttype}}</td></tr>
              <tr class=""><td>FQDN</td><td>{{server_detail.fqdn}}</td></tr>
              <tr class=""><td>IPAddress</td><td>{{server_detail.ipaddress}}</td></tr>
              <tr class=""><td>Domain</td><td>{{server_detail.domain}}</td></tr>
              <tr class=""><td>IsStandaloneServer</td><td>{{server_detail.isstandaloneserver}}</td></tr>
              <tr class=""><td>IsSqlClusterNode</td><td>{{server_detail.issqlclusternode}}</td></tr>
              <tr class=""><td>IsAgNode</td><td>{{server_detail.isagnode}}</td></tr>
              <tr class=""><td>IsWSFC</td><td>{{server_detail.iswsfc}}</td></tr>
              <tr class=""><td>IsSqlCluster</td><td>{{server_detail.issqlcluster}}</td></tr>
              <tr class=""><td>IsAG</td><td>{{server_detail.isag}}</td></tr>
              <tr class=""><td>ParentServerId</td><td>{{server_detail.parentserverid}}</td></tr>
              <tr class=""><td>OS</td><td>{{server_detail.os}}</td></tr>
              <tr class=""><td>SPVersion</td><td>{{server_detail.spversion}}</td></tr>
              <tr class=""><td>IsVM</td><td>{{server_detail.isvm}}</td></tr>
              <tr class=""><td>IsPhysical</td><td>{{server_detail.isphysical}}</td></tr>
              <tr class=""><td>Manufacturer</td><td>{{server_detail.manufacturer}}</td></tr>
              <tr class=""><td>Model</td><td>{{server_detail.model}}</td></tr>
              <tr class=""><td>RAM</td><td>{{server_detail.ram}}</td></tr>
              <tr class=""><td>CPU</td><td>{{server_detail.cpu}}</td></tr>
              <tr class=""><td>Powerplan</td><td>{{server_detail.powerplan}}</td></tr>
              <tr class=""><td>OSArchitecture</td><td>{{server_detail.osarchitecture}}</td></tr>
              <tr class=""><td>ISDecom</td><td>{{server_detail.isdecom}}</td></tr>
              <tr class=""><td>DecomDate</td><td>{{server_detail.decomdate}}</td></tr>
              <tr class=""><td>GeneralDescription</td><td>{{server_detail.generaldescription}}</td></tr>
              <tr class=""><td>Remark1</td><td>{{server_detail.remark1}}</td></tr>
              <tr class=""><td>Remark2</td><td>{{server_detail.remark2}}</td></tr>
              <tr class=""><td>CollectionDate</td><td>{{server_detail.collectiondate}}</td></tr>
              <tr class=""><td>CollectedBy</td><td>{{server_detail.collectedby}}</td></tr>
              <tr class=""><td>UpdatedDate</td><td>{{server_detail.updateddate}}</td></tr>
              <tr class=""><td>UpdatedBy</td><td>{{server_detail.updatedby}}</td></tr>
            </tbody>
          </table>

          <h6>SqlInstances:</h6>
          <ul>
          {% for instance in server_detail.sqlinstances.all %}
            <li><a href="#">{{instance.sqlinstance}}</a></li>
          {% endfor %}
          <ul>
          
          <p>
          <div class="container">
            <a href="{% url 'mssql:serverupdate' pk=server_detail.pk %}" class="btn btn-warning">Update</a>
            <a href="{% url 'mssql:serverdelete' pk=server_detail.pk %}" class="btn btn-danger">Delete</a>
          </div>
          </p>
        </p>
      </div>
    </div>
  </div>
{% endblock block_body %}

mssql/templates/mssql/folder/object_form.html
{% extends "mssql/mssql_base.html" %}
{% load staticfiles %}

{% block block_navigation %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:index' %}">MSSQL</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:server' %}">Server</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% if not form.instance.pk %} Create {% else %} Update {% endif %}</li>
    </ol>
  </nav>
{% endblock block_navigation %}

{% block block_body %}
  <div class="container">
    <div class="card">
      <h5 class="card-header">{% if not form.instance.pk %} Create {% else %} Update {% endif %} Server</h5>
      <div class="card-body">
        <h5 class="card-title">{% if not form.instance.pk %} Kindly provide details of new Server:- {% else %} Kindly make the required changes:- {% endif %}</h5>
        
        <form method="POST">
          {% csrf_token %}
          <p class="card-text">
            {% include "form_snippet.html" with form=form %}
          </p>
          <input type="submit" class="btn btn-primary" value="Submit">
        </form>
      
      </div>
    </div>
  </div>
{% endblock block_body %}

mssql/templates/mssql/folder/object_list.html
{% extends "mssql/mssql_base.html" %}
{% load staticfiles %}

{% block block_navigation %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:index' %}">MSSQL</a></li>
      <li class="breadcrumb-item active" aria-current="page">Server</li>
    </ol>
  </nav>
{% endblock block_navigation %}

{% block block_body %}
<div class="container-fluid">
  {% if servers %}
    <div class="table-responsive">
      <!-- <table id="tivotabledata" class="table table-bordered table-hover table-sm tivotabledata">  -->
      <table id="dbinventorytable" class="dbinventorytable-list">  
        <thead>
          <tr class="table-primary">
            <th scope="col">ServerID</th>
            <th scope="col">ServerName</th>
            <th scope="col">ApplicationId</th>
            <th scope="col">EnvironmentType</th>
            <th scope="col">FQDN</th>
            <th scope="col">IPAddress</th>
            <th scope="col">Domain</th>
            <th scope="col">IsStandaloneServer</th>
            <th scope="col">IsSqlClusterNode</th>
            <th scope="col">IsAgNode</th>
            <th scope="col">IsWSFC</th>
            <th scope="col">IsSqlCluster</th>
            <th scope="col">IsAG</th>
            <th scope="col">ParentServerId</th>
            <th scope="col">OS</th>
            <th scope="col">SPVersion</th>
            <th scope="col">IsVM</th>
            <th scope="col">IsPhysical</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">RAM</th>
            <th scope="col">CPU</th>
            <th scope="col">Powerplan</th>
            <th scope="col">OSArchitecture</th>
            <th scope="col">ISDecom</th>
            <th scope="col">DecomDate</th>
            <th scope="col">GeneralDescription</th>
            <th scope="col">Remark1</th>
            <th scope="col">Remark2</th>
            <th scope="col">CollectionDate</th>
            <th scope="col">CollectedBy</th>
            <th scope="col">UpdatedDate</th>
            <th scope="col">UpdatedBy</th>
          </tr>
        </thead>
        <tbody class="table-hover">
        {% for server in servers %}
          <tr>
            <td><a href="{{server.serverid}}">{{server.serverid}}</a></td>
            <td><a href="{{server.serverid}}">{{server.servername}}</a></td>
            <td> 
              {% if server.applicationid %}
              <a href="{% url 'mssql:applicationdetail' server.applicationid.pk %}">{{server.applicationid}}</a>
              {% else %}
                {{server.applicationid}}
              {% endif %}
            </td>
            <td>{{server.environmenttype}}</td>
            <td>{{server.fqdn}}</td>
            <td>{{server.ipaddress}}</td>
            <td>{{server.domain}}</td>
            <td>{{server.isstandaloneserver}}</td>
            <td>{{server.issqlclusternode}}</td>
            <td>{{server.isagnode}}</td>
            <td>{{server.iswsfc}}</td>
            <td>{{server.issqlcluster}}</td>
            <td>{{server.isag}}</td>
            <td>
              {% if server.parentserverid %}
              <a href="{{server.parentserverid}}">{{server.parentserverid}}</a>
              {% else %}
                {{server.parentserverid}}
              {% endif %}
            </td>
            <td>{{server.os}}</td>
            <td>{{server.spversion}}</td>
            <td>{{server.isvm}}</td>
            <td>{{server.isphysical}}</td>
            <td>{{server.manufacturer}}</td>
            <td>{{server.model}}</td>
            <td>{{server.ram}}</td>
            <td>{{server.cpu}}</td>
            <td>{{server.powerplan}}</td>
            <td>{{server.osarchitecture}}</td>
            <td>{{server.isdecom}}</td>
            <td>{{server.decomdate}}</td>
            <td>{{server.generaldescription}}</td>
            <td>{{server.remark1}}</td>
            <td>{{server.remark2}}</td>
            <td>{{server.collectiondate}}</td>
            <td>{{server.collectedby}}</td>
            <td>{{server.updateddate}}</td>
            <td>{{server.updatedby}}</td>
          </tr>
        {% endfor %}
        </tbody>
        <tfoot>
          <tr class="table-primary">
            <th scope="col">ServerID</th>
            <th scope="col">ServerName</th>
            <th scope="col">ApplicationId</th>
            <th scope="col">EnvironmentType</th>
            <th scope="col">FQDN</th>
            <th scope="col">IPAddress</th>
            <th scope="col">Domain</th>
            <th scope="col">IsStandaloneServer</th>
            <th scope="col">IsSqlClusterNode</th>
            <th scope="col">IsAgNode</th>
            <th scope="col">IsWSFC</th>
            <th scope="col">IsSqlCluster</th>
            <th scope="col">IsAG</th>
            <th scope="col">ParentServerId</th>
            <th scope="col">OS</th>
            <th scope="col">SPVersion</th>
            <th scope="col">IsVM</th>
            <th scope="col">IsPhysical</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">RAM</th>
            <th scope="col">CPU</th>
            <th scope="col">Powerplan</th>
            <th scope="col">OSArchitecture</th>
            <th scope="col">ISDecom</th>
            <th scope="col">DecomDate</th>
            <th scope="col">GeneralDescription</th>
            <th scope="col">Remark1</th>
            <th scope="col">Remark2</th>
            <th scope="col">CollectionDate</th>
            <th scope="col">CollectedBy</th>
            <th scope="col">UpdatedDate</th>
            <th scope="col">UpdatedBy</th>
          </tr>
        </tfoot>
      </table>
    </div>
  {% else %}
    <p> No data to display</p>
  {% endif %}
</div>

{% endblock block_body %}