databaseinventory/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from users import views as usr_views
from mssql import views as tsql_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    url(r'^mssql/', include('mssql.urls',namespace='mssql'), name='mssql'),
    url(r'^users/', include('users.urls',namespace='users'), name='users'),
    url(r'^logout/$', usr_views.user_logout, name = 'logout'),
]

admin.site.site_header = 'DbInventory administration'

mssql/urls.py
# from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url
from mssql import views

# TEMPLATE URLS!
app_name = 'mssql'


# https://docs.djangoproject.com/en/2.1/ref/urls/
# https://docs.djangoproject.com/en/2.1/topics/http/urls/
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), 
    # dbo.Application
    path('application/',views.ApplicationListView.as_view(),name='application'),
    path('application/<int:pk>/', views.ApplicationDetailView.as_view(),name='applicationdetail'),
    path('application/create/', views.ApplicationCreateView.as_view(), name='applicationcreate'),
    path('application/update/<int:pk>/', views.ApplicationUpdateView.as_view(), name='applicationupdate'),
    path('application/delete/<int:pk>/', views.ApplicationDeleteView .as_view(), name='applicationdelete'),
    # dbo.Server
    # path('server/',views.server,name='server'),
    path('server/',views.ServerListView.as_view(),name='server'),
    path('server/<int:pk>/', views.ServerDetailView.as_view(),name='serverdetail'),
    path('server/create/', views.ServerCreateView.as_view(), name='servercreate'),
    path('server/update/<int:pk>/', views.ServerUpdateView.as_view(), name='serverupdate'),
    path('server/delete/<int:pk>/', views.ServerDeleteView .as_view(), name='serverdelete'),
    # dbo.Instance
    path('instance/', views.InstanceListView.as_view(), name='instance'),
    path('instance/<int:pk>/', views.InstanceDetailView.as_view(),name='instancedetail'),
    path('instance/create/', views.InstanceCreateView.as_view(), name='instancecreate'),
    path('instance/update/<int:pk>/', views.InstanceUpdateView.as_view(), name='instanceupdate'),
    path('instance/delete/<int:pk>/', views.InstanceDeleteView .as_view(), name='instancedelete'),
    # dbo.Databases
    path('database/', views.DatabaseListView.as_view(), name='database'),
    path('database/<int:pk>/', views.DatabaseDetailView.as_view(),name='databasedetail'),
    path('database/create/', views.DatabaseCreateView.as_view(), name='databasecreate'),
    path('database/update/<int:pk>/', views.DatabaseUpdateView.as_view(), name='databaseupdate'),
    path('database/delete/<int:pk>/', views.DatabaseDeleteView .as_view(), name='databasedelete'),
    # dbo.Backupschedule
    path('backupschedule/',views.BackupscheduleListView.as_view(),name='backupschedule'),
    path('backupschedule/<int:pk>/', views.BackupscheduleDetailView.as_view(),name='backupscheduledetail'),
    path('backupschedule/create/', views.BackupscheduleCreateView.as_view(), name='backupschedulecreate'),
    path('backupschedule/update/<int:pk>/', views.BackupscheduleUpdateView.as_view(), name='backupscheduleupdate'),
    path('backupschedule/delete/<int:pk>/', views.BackupscheduleDeleteView .as_view(), name='backupscheduledelete'),
    # dbo.Commandqueue
    path('commandqueue/',views.CommandqueueListView.as_view(),name='commandqueue'),
    path('commandqueue/<int:pk>/', views.CommandqueueDetailView.as_view(),name='commandqueuedetail'),
    path('commandqueue/create/', views.CommandqueueCreateView.as_view(), name='commandqueuecreate'),
    path('commandqueue/update/<int:pk>/', views.CommandqueueUpdateView.as_view(), name='commandqueueupdate'),
    path('commandqueue/delete/<int:pk>/', views.CommandqueueDeleteView .as_view(), name='commandqueuedelete'),
    # dbo.Logging
    path('logging/', views.LoggingListView.as_view(), name='logging'),
    path('logging/<int:pk>/', views.LoggingDetailView.as_view(),name='loggingdetail'),
    path('logging/create/', views.LoggingCreateView.as_view(), name='loggingcreate'),
    path('logging/update/<int:pk>/', views.LoggingUpdateView.as_view(), name='loggingupdate'),
    path('logging/delete/<int:pk>/', views.LoggingDeleteView .as_view(), name='loggingdelete'),
    # dbo.Backuphistory
    path('backuphistory/', views.BackuphistoryListView.as_view(), name='backuphistory'),
    path('backuphistory/<int:pk>/', views.BackuphistoryDetailView.as_view(),name='backuphistorydetail'),
]

users/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from users import views

# TEMPLATE URLS!
app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'signup', views.signup, name='signup'),
    url(r'^register/$', views.user_register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    # url(r'^logout/$', views.user_logout, name = 'user_logout'),
    # url(r'special/', views.special, name = 'special'),
    #url(r'signup', views.signup, name='signup'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    # https://stackoverflow.com/a/24936834/4449743
    # activation_key = models.CharField(max_length=40)
    # key_expires = models.DateTimeField()

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import UserProfileInfo
from django.core import validators


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    # class Meta():
    #     model = User
    #     fields = ('username', 'password')


def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name should start with letter Z")


class FormName(forms.Form):
    # name = forms.CharField(validators=[check_for_z])
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Confirm Email")
    # botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[
    #                              validators.MaxLengthValidator(0)])
    text = forms.CharField(widget=forms.Textarea)

    

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail = all_clean_data['verify_email']
        if email != vemail:
            raise validators.ValidationError("MAKE SURE EMAILS MATCH!")

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("GOTCHA BOT!")
    #     return botcatcher

users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

from users.forms import UserForm, UserProfileInfoForm, LoginForm
#from django.contrib.auth.models import User
from django.db import connection
import json
from databaseinventory.utils import dictfetchall
from ImportantSettings import EmailUser, AdminEmail

# Create your views here.


def index(request):
    return render(request, 'users/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


def user_login(request):
    loggedin = False

    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)

        if login_form.is_valid():
            #username = login_form.cleaned_data['username']
            username = login_form.cleaned_data['username']
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    loggedin = True
                    return HttpResponseRedirect(reverse('projectindex'))
                else:
                    return HttpResponse("Account Not Active")
            else:
                print("Someone tried to login and failed!")
                print("Username: {0} and password {1}".format(
                    username, password))
                return HttpResponse("Invalid login details supplied!")

            # If form is Valid, then
            emailmessage = "username ["+username + \
                "] tried to login in SQLDBATools portal with password '"+password+"'."
            admin_email = 'ajay.dwivedi@tivo.com'

            send_mail('Registration - SQLDBAToolsInventory',
                      emailmessage,
                      'SQLDBATools@tivo.com',
                      [admin_email],
                      fail_silently=False,
                      )

        else:
            print("Invalid details submitted!")
            return HttpResponse("Form details are not valid!")

    else:
        login_form = LoginForm()
        return render(request, 'users/login.html', {'login_form': login_form,
                                                    'loggedin': loggedin,
                                                    }
                      )


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('projectindex'))


def user_register(request):
    #registered = False
    user_form = None
    profile_form = None

    returnSuccessMessage = None
    returnErrorMessage = None

    if request.method == "POST":
        userName = request.POST.get('username')
        userEmail = request.POST.get('email')

        print("UserName being registered = {0}".format(userName))

        cursor = connection.cursor()
        cursor.execute("select username, email from [auth_user] as u where u.username = '{0}' or email = '{1}'".format(
            userName, userEmail))

        userObj = dictfetchall(cursor)

        if userObj:
            returnErrorMessage = list()
            for usr in userObj:
                if usr['email'] == userEmail:
                    msg = "Email [{1}] is already taken by UserName [{0}].".format(
                        usr['username'], usr['email'])
                else:
                    msg = "UserName [{0}] is already registered with email [{1}].".format(
                        usr['username'], usr['email'])
                msgDict = {'errMessage': msg}
                returnErrorMessage.append(msgDict)
        else:
            user_form = UserForm(data=request.POST)
            profile_form = UserProfileInfoForm(data=request.POST)

            if user_form.is_valid() and profile_form.is_valid():
                userName = user_form.cleaned_data['username']
                userEmail = user_form.cleaned_data['email']
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user = user

                if 'profile_pic' in request.FILES:
                    profile.profile_pic = request.FILES['profile_pic']

                profile.save()

                recipient_list = [EmailUser, AdminEmail, userEmail]
                mailMessage = """
Hi {0},

Thanks for registering in SQLDBATools portal. We are verifying your details.


Thanks & Regards,
SQLDBATools
""".format(userEmail)

                send_mail('User Registration - SQLDBAToolsInventory',
                          mailMessage,
                          EmailUser,
                          recipient_list,
                          fail_silently=False,
                          )

                returnSuccessMessage = "UserName [{0}] is successfully registered with email [{1}].".format(
                    userName, userEmail)
            else:
                print(user_form.errors, profile_form.errors)
                returnErrorMessage = user_form.errors + profile_form.errors
                # redirect('cfman:ServerAdd')
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    if returnErrorMessage:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    print("returnErrorMessage = '{0}'".format(returnErrorMessage))

    context_user = {'user_form': user_form,
                    'profile_form': profile_form,
                    'returnSuccessMessage': returnSuccessMessage,
                    'returnErrorMessage': returnErrorMessage,
                    # 'registered': registered,

                    }

    return render(request, 'users/registration.html', context=context_user)


'''
def signup(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            # Do Something
            print("Validation Success")
            print("Name: "+form.cleaned_data['name'])
            print("Email: "+form.cleaned_data['email'])
            print("Text: "+form.cleaned_data['text'])
            send_mail('Signup - SQLDBATools',
                      'Thanks for signing up for SQLDBATools portal. We are verifying your details.',
                      'SQLDBATools@tivo.com',
                      [form.cleaned_data['email']],
                      fail_silently=False,
                      )

    return render(request, 'loginauth/signup.html', {'form': form})
'''

templates/users/base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block block_autoloader %}
  <script>
    $("#navbarSupportedContent").find(".active").removeClass("active")
    // $("#mssql").addClass("active")
  </script>
{% endblock block_autoloader %}

templates/users/index.html
{% extends "users/base.html" %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1> User Page </h1>
    </div>
  </div>
{% endblock body_block %}

templates/users/login.html
{% extends "users/base.html" %}

{% block body_block %}
<div class="jumbotron">

  {% if loggedin %}
    <h1> You have successfully logged in! </h1>
  {% else %}
    <h1>Please Login</h1>
</div>

<div class="container card">
  <form action="{% url 'users:user_login' %}" enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  <div class="card-body">
    <h5 class="card-title">Kindly provide login details:-</h5>
    <p class="card-text">{% include "form_snippet.html" with form=login_form %}</p>
    <input type="submit" name="" value="Login"  class="btn btn-primary col-auto">
  </div>
  <div class="card-body">
    <p>If you are a new user, then <a href="{% url 'users:register' %}" class="btn btn-primary">Register</a></p>
  </div>
  </form>
  <div class="card-footer text-muted">
    <p>The time is {% now "d-M-Y g:i a T" %}</p>
    {% comment %} {% load tz %}
        The UTC time is {{ object.date }}
    {% localtime on %}
        The local time is {{ object.date }}
    {% endlocaltime %} {% endcomment %}
  </div>
</div>
  {% endif %}
{% endblock body_block %}

templates/users/registration.html
{% extends "users/base.html" %}

{% block page_navigator %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'projectindex' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mssql:index' %}">User</a></li>
      <li class="breadcrumb-item active" aria-current="page">Register</li>
    </ol>
  </nav>
{% endblock page_navigator %}

{% block body_block %}
  <div class="container">
    <div class="card">
      <h5 class="card-header">Register Here!</h5>
      <div class="card-body">

        {% if returnSuccessMessage %}
          <h5 class="card-title">{{ returnSuccessMessage }}</h5>
        {% else %}
          {% if user_form %}
            <h5 class="card-title">Kindly fill out below user registration form:-</h5>

            {% if returnErrorMessage %}
              <div class="text-danger">
                <ul>
                {% for msg in returnErrorMessage %}
                    <li>{{msg.errMessage}}</li>
                {% endfor returnErrorMessage %}
                </ul>
              </div>
            {% endif %}

            <form method="POST">
              {% csrf_token %}
              <p class="card-text">
                {% comment %} {{ form.as_p }} {% endcomment %}
                {% include "form_snippet.html" with form=user_form %}
                {% include "form_snippet.html" with form=profile_form %}
              </p>
              <input type="submit" name="Register" value="Register"  class="btn btn-primary col-auto">
            </form>
          {% endif %}
        {% endif %}
      
      </div>
    </div>
  </div>
{% endblock body_block %}

templates/users/registration_bak.html
{% extends "users/base.html" %}

{% block body_block %}

<div class="jumbotron">

  {% if registered %}
    <h1> Thank you for registering! </h1>
  {% else %}
    <h1>Register Here!</h1>
</div>
<div class="container">
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {% include "form_snippet.html" with form=user_form %}
      {% include "form_snippet.html" with form=profile_form %}
      
      <input type="submit" name="" value="Register"  class="btn btn-primary col-auto">
      
    </form>
  {% endif %}
</div>
{% endblock body_block %}